#+Title: Settings
#+filetags: :emacs:init:
#+options: toc:2
#+startup: showeverything

This is an attempt to use /literate org mode/.
It's purpose is to have a "/self-documenting/" Emacs configuration.

To run a code block use ~C-c C-c~.

* General Information

** Setting defaults for ~org-babel~

This would set /all/ =src= blocks to be:

1. =emacs-lisp=
2. write the =src= blocks out to =./scratch.el=

#+begin_src org
#+PROPERTY: header-args:emacs-lisp:tangle ./scratch.el
#+end_src

* Experimenting

#+begin_src emacs-lisp :noeval
(setq display-fill-column-indicator-column 80)
#+end_src

This requires a /cons cell/ (~(val . val~).
Syntax is this:

- ~(fn '(val . val))~, mind the =~=!

#+begin_src emacs-lisp :noeval
(fringe-mode '(50 . 25))
#+end_src

* ~init.el~

This is the code that needs to go into =init.el=.

#+begin_src emacs-lisp
  ;; ;; This reads in the org file at:
  ;; ;; - ~/.config/emacs/settings.org
  ;; ;; The "original" path is at:
  ;; ;; - ~/src/dotfiles/dot-config/emacs/settings.org
  ;; (org-babel-load-file
  ;;  (expand-file-name
  ;;   "settings.org"
  ;;   user-emacs-directory))
#+end_src

** TODO Find out how to tangle ==init.el==

When we activate this,
we run into a recursion problem.

*GOAL*: It would be nice to:
  1) Tangle this into the actual =init.el= file
  2) */not/* run into any recursion problems

* Helper Functions

#+begin_src emacs-lisp
;; Contains AI-generated code
;; MODEL USED: Claude Sonnet 4.5

(defun serverhorror/find-home-directory ()
  "Return the 'HOME' directory of the user running"
  (interactive)
  ;; Example: Run OS-specific code in Emacs Lisp
  (cond
   ;; Linux or macOS settings
   ((or (eq system-type 'gnu/linux)
	(eq system-type 'darwin))
    "~")

   ;; Windows-specific settings here
   ((eq system-type 'windows-nt)
    (getenv "USERPROFILE"))
   ))

;; (provide 'serverhorror/find-home-directory)
#+end_src

#+begin_src emacs-lisp
(defun serverhorror/nuke-trailing-spaces ()
  (add-hook 'before-save-hook #'delete-trailing-whitespace nil t))

;; (provide 'serverhorror/nuke-trailing-spaces)
#+end_src

* UI Tweaks

** General Settings

#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

** Load the Theme

#+begin_src emacs-lisp
(load-theme 'modus-vivendi)
#+end_src

#+begin_src emacs-lisp
;; ;; Change the font to what I like
(set-frame-font "FiraCode Nerd Font Mono Ret-12")
;; ; (set-default-font "FiraCode Nerd Font Mono Ret-24") ; this is for old emacs versions!
;; (set-face-font 'mode-line "Fira Code Nerd Font Mono Ret-10")
;; (set-face-background 'mode-line-inactive "gray") ;; is this smart?
;; (set-face-font 'mode-line-inactive  "Fira Code Nerd Font Mono Ret-10")
#+end_src

* General Text Editing Behaviour

This adds a hook.
The hook will file /before/ save happens.

#+begin_src emacs-lisp
  (add-hook 'before-save-hook #'delete-trailing-whitespace nil t)
#+end_src

This adds a hook.
The hook will happen /only/ for ~'prog-mode~

#+begin_src emacs-lisp
;; (add-hook 'prog-mode-hook #'serverhorror/nuke-trailing-spaces)
#+end_src

#+begin_src emacs-lisp
  (setopt use-short-answers t) ; yes-or-no becomes y-or-n
#+end_src

** Show Trailing Whitespace, Lines, ...

#+begin_src emacs-lisp
  (setq-default show-trailing-whitespace t)
  ;; (require 'whitespace)
  ;; (setq whitespace-style '(face tabs trailing lines space-before-tab newline  space-after-tab space-mark tab-mark))
  ;; (setq whitespace-display-mappings
  ;;      '(
  ;;        ;; (space-mark 32 [183] [46])
  ;;        (newline-mark 10 [182 10])
  ;;        (tab-mark 9 [9655 9] [92 9])))
  ;; (global-whitespace-mode 1)

#+end_src

#+begin_src emacs-lisp
  (setq-default word-wrap nil)
  (setq-default truncate-lines t)
#+end_src

#+begin_src emacs-lisp
  (setq mode-require-final-newline t) ; Yes! We want a new line at the end of the file!
  (setq delete-trailing-lines t) ; delete extra trailing lines
#+end_src

*** TODO Remove all trailing whitepaces, lines, ...

** Save and Auto Save

#+begin_src emacs-lisp
  (setq auto-save-default nil) ; Instruct auto-save-mode to save to the current file, not a backup file
  ;; Disable auto-save
  (auto-save-mode -1)
#+end_src

** Other Core Settings
#+begin_src emacs-lisp
  ;; Core settings
  (setq make-backup-files nil) ; No backup files, please
  (setq line-move-visual t) ; we do not like this!
  (setq make-backup-files nil) ; Disable backup files
  (setq truncate-lines t) ; asdf asdf asdf  asdf asdf asdf  asdf asdf asdf  asdf asdf asdf  asdf asdf asdf  asdf asdf asdf  asdf asdf asdf

  ;; Enable auto-save for the actual file
  (auto-save-visited-mode t)

  ;; Disable menu-, tool- and scroll-bar

  ;; Other useful stuff; Do "C-h f"
  (blink-cursor-mode t)
  (global-hl-line-mode t)
  (global-display-line-numbers-mode t)
  (column-number-mode t)
  (show-paren-mode t)
  ;; Remember recently opened files
  (recentf-mode t)
#+end_src
* Customiziation File

This makes sure that the /customization/ file does not get in the way.

#+begin_src emacs-lisp
;; Make sure the customiziations from the GUI
;; do not mess up what we want to set
(setq custom-file (concat user-emacs-directory "custom.el"))
#+end_src

We do _not_ want this to actually happen

#+begin_src emacs-lisp :noeval
(when (file-exists-p custom-file)
  (load custom-file))
#+end_src

* Emacs Server and ~emacsclient~
** Make sure the Emacs server is running

#+begin_src emacs-lisp
  ;; We want an emacs-server to be running, and
  ;; even if it wasn't started with "emacs --daemon"
  (require 'server) ; Ensure the server module is loaded
  (unless (server-running-p)
    (server-start)) ; Start the server only if it's not already running
#+end_src

** How does this work?

This allows us to use ~emacsclient~.
To use emacs in this setting:

#+begin_src shell :noeval
  emacsclient --reuse-frame --alternate-editor="emacs"
#+end_src

*** TODO Make sure that our =editor= is set to use this by default

* Package Manager

#+begin_src emacs-lisp
  ;; Configure packages and add MELPA to the list of repos...
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  ;; ;Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
  ;; ;and `package-pinned-packages`. Most users will not need or want to do this.
  ;; (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
  (package-initialize)
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
  ;; ;; Make sure we always set the ':ensure t' for all packages
  ;; (eval-and-compile
  ;;   (setq use-package-always-ensure t
  ;;  use-package-expand-minimally t))
  (setq use-package-always-ensure t)
#+end_src

** TODO Emacs Modes
*** TODO Emacs Zen Modes                                         :emacs:kb:

- [[https://github.com/joostkremers/writeroom-mode][writeroom-mode]]
- [[https://github.com/joaotavora/darkroom][Darkroom]]
- [[https://github.com/rnkn/olivetti][Olivetti]]

*** Other things

- [[https://github.com/andre-r/centered-cursor-mode.el][centered-cursor-mode]]
  Keeps the cursor in the center.
  This seems to *not* work when going to the top of the file
- [[https://github.com/trevorpogue/topspace][topspace]]

  :README:
  TopSpace is an Emacs minor mode that lets you display a buffer's first line in the center of a window instead of just at the top. This is done by automatically drawing an upper margin/padding above line 1 as you recenter and scroll it down.

  Features
    - Easier on the eyes:
      Recenter or scroll down top text to a more comfortable eye level for reading,
      especially when in full-screen or on a large monitor.
    - Easy to use:
      No new keybindings are required,
      keep using all your previous scrolling & recentering commands,
      except now you can also scroll down the first line.
      It also integrates seamlessly with =centered-cursor-mode=
      to keep the cursor centered all the way to the first line.
  :END:


  Look at this setting:

  #+begin_src emacs-lisp :noeval
    (setq ccm-recenter-at-end-of-file t)
  #+end_src

*** Scrolling

#+begin_src emacs-lisp :noeval
  (setq scroll-margin 10)
#+end_src

* Evil Mode (vim)

#+begin_src emacs-lisp
  (use-package evil
    :ensure t
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    :config
    (evil-mode t))

  (use-package evil-collection
    :ensure t
    :after evil
    :config
    (evil-collection-init))
#+end_src

#+begin_src emacs-lisp
  (global-set-key (kbd "<C-tab>") 'other-window)
  (global-set-key (kbd "<C-w> j") 'other-window)
  (global-set-key (kbd "<C-w> k") 'other-window)
#+end_src

* ~org~ and ~org-roam~ :org:

*** ~org~ mode

#+begin_src emacs-lisp
  ;; This assumes you've installed the package via MELPA.
  ;; org, org-roam mode
  ;; org-roam is a full management for a directory
  (use-package org
    :demand t
    :ensure t
    :init
    (setq org-directory
  	(expand-file-name "src/brain" (serverhorror/find-home-directory)))
    (setq org-agenda-files (
  			  list
  			  (expand-file-name "src/brain" (serverhorror/find-home-directory))
  			  (expand-file-name "src/brain" (serverhorror/find-home-directory))
  			  ))
    (setq org-refile-targets '((org-agenda-files :maxlevel . 2)))
    (setq org-startup-indented t)
    (setq org-startup-numerated t)
    (setq org-hide-leading-stars t)
    (setq org-log-done "time"))
    ;; (setq org-startup-folded t) ; no that is annoying
#+end_src

*** ~org-roam~

#+begin_src emacs-lisp
  (use-package org-roam
    :demand t
    :ensure t
    :custom
    (org-roam-directory
     (expand-file-name "src/brain" (serverhorror/find-home-directory)))
    (org-roam-complete-everywhere t)
    :bind (
  	 ("C-c n c" . org-roam-capture)
  	 ("C-c n d" . org-roam-dailies-capture-today)
  	 ("C-c n f" . org-roam-node-find)
  	 ("C-c n i" . org-roam-node-insert)
  	 :map org-mode-map
  	 ("C-c n l" . org-roam-buffer-toggle)
  	 )
    :config
    (org-roam-setup)
    (org-roam-db-autosync-enable))
#+end_src

*** Structure Templates

This allows us to type ~<el TAB~ and it expands to a /full/ =src= block:

#+begin_src emacs-lisp
  (require 'org-tempo)
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  (add-to-list 'org-structure-template-alist '("go" . "src go"))
#+end_src

*** Mermaid Previews in ~org-mode~ >> ~ob-mermaid~

#+begin_src emacs-lisp
  (use-package ob-mermaid
    :ensure t)
#+end_src

* Auto Complete

#+begin_src emacs-lisp
  ;; Enable Vertico.
  (use-package vertico
    :ensure t
    :custom
    ;; (vertico-scroll-margin 0) ;; Different scroll margin
    ;; (vertico-count 20) ;; Show more candidates
    (vertico-resize t) ;; Grow and shrink the Vertico minibuffer
    (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
    :init
    (vertico-mode))
#+end_src

* Save History over Restarts

This let's me cycle thru, e.g., =find-file= right after opening Emacs.
It will still show the /old/ entries.

#+begin_src emacs-lisp
  ;; Persist history over Emacs restarts. Vertico sorts by history position.
  (use-package savehist
    :ensure t
    :init
    (savehist-mode))
#+end_src

* TODO orderless

No idea what it is for!

* [[https://github.com/oantolin/orderless][Emacs completion style that matches multiple regexps in any order (github.com)]]

#+begin_src emacs-lisp
;; ;; Optionally use the `orderless' completion style.
;; (use-package orderless
;;   :ensure t
;;   :custom
;;   ;; Configure a custom style dispatcher (see the Consult wiki)
;;   ;; (orderless-style-dispatchers '(+orderless-consult-dispatch orderless-affix-dispatch))
;;   ;; (orderless-component-separator #'orderless-escapable-split-on-space)
;;   (completion-styles '(orderless basic))
;;   (completion-category-overrides '((file (styles partial-completion))))
;;   (completion-category-defaults nil) ;; Disable defaults, use our settings
;;   (completion-pcm-leading-wildcard t)) ;; Emacs 31: partial-completion behaves like substring
#+end_src
* Original ~init.el~


#+begin_src emacs-lisp
;; (add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

;;
;;
;; ;; Remove the initial startup screen so we start directly in the scratch buffer
;; (setq inhibit-startup-screen t)
;; ;;(setq frame-title-format "%b")
;;
;; ;; ;; I Do Things ...
;; ;; (ido-mode t)
;; ;; (ido-everywhere t) ; no idea what this actually does ...
;;
;; ;; (add-to-list 'default-frame-alist '(undecorated . t))
;; ;; (add-to-list 'default-frame-alist '(alpha-background . 90))
;; ;; (add-to-list 'default-frame-alist '(alpha-background . 95))
;;
;; ;; Show line numbers everywhere
;; (global-display-line-numbers-mode t)
;; (setq display-line-numbers-type 'relative)
;; ;; Exclude these from showing line numbers
;; (dolist (mode '(
;;      eshell-mode-hook
;;      help-mode-hook
;;      term-mode-hook
;;      which-key-mode-hook
;;      org-mode-hook
;;      eww-mode-hook
;;      ))
;;   (add-hook mode(lambda () (display-line-numbers-mode 0))))
;;
;;
;;
;; ;; Tests for ligatures:
;; ;; >=  != ==
;;
;;
;; ;; Some nicer Keybindings!
;
;; ;; ;; Configure packages and add MELPA to the list of repos...
;; ;; (require 'package)
;; ;; (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; ;; ;; ;Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
;; ;; ;; ;and `package-pinned-packages`. Most users will not need or want to do this.
;; ;; ;; (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
;; ;; (package-initialize)
;; ;; (unless (package-installed-p 'use-package)
;; ;;   (package-refresh-contents)
;; ;;   (package-install 'use-package))
;; ;; ;; ;; Make sure we always set the ':ensure t' for all packages
;; ;; ;; (eval-and-compile
;; ;; ;;   (setq use-package-always-ensure t
;; ;; ;;    use-package-expand-minimally t))
;; ;; (setq use-package-always-ensure t)
;;
;;
;;
;; ;; Emacs minibuffer configurations.
;; (use-package emacs
;;   :ensure t
;;   :custom
;;   ;; Enable context menu. `vertico-multiform-mode' adds a menu in the minibuffer
;;   ;; to switch display modes.
;;   (context-menu-mode t)
;;   ;; Support opening new minibuffers from inside existing minibuffers.
;;   (enable-recursive-minibuffers t)
;;   ;; Hide commands in M-x which do not work in the current mode.  Vertico
;;   ;; commands are hidden in normal buffers. This setting is useful beyond
;;   ;; Vertico.
;;   (read-extended-command-predicate #'command-completion-default-include-p)
;;   ;; Do not allow the cursor in the minibuffer prompt
;;   (minibuffer-prompt-properties
;;    '(read-only t cursor-intangible t face minibuffer-prompt)))
;;
;;
;; (use-package magit
;;   :ensure t)
;;

;; (use-package eglot
;;   :ensure t
;;   :defer t
;;   :hook ((python-mode . eglot-ensure)
;;          (go-mode . eglot-ensure))
;;   :config
;;   (add-to-list 'eglot-server-programs
;;                `(python-mode
;;                  . ,(eglot-alternatives '(("pyright-langserver" "--stdio")
;;                                           "jedi-language-server"
;;                                           "pylsp")))))
;;
;;
;; (defun serverhorror/org-mode-prettify-symbols ()
;;   "Visually replace leading stars in Org headings."
;;   (setq prettify-symbols-alist
;;  '(
;;    ("*" . "⋕")
;;    ))
;;   (prettify-symbols-mode 1))
;; (add-hook 'org-mode-hook #'serverhorror/org-mode-prettify-symbols)
;;
;; (defun serverhorror/case-insensitive-org-roam-node-read (orig-fn &rest args)
;;   (let ((completion-ignore-case t))
;;     (apply orig-fn args)))
;; (advice-add 'org-roam-node-read :around #'serverhorror/case-insensitive-org-roam-node-read)
#+end_src
